name: home
description: "home æ¨¡å—"
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../basic/core
  network:
    path: ../../basic/network
  router_path:
    path: ../router_path
  assets:
    path: ../assets


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
